### PR TITLE
fix: update splash logo

### PR DESCRIPTION
**Pull request by DanielJoyce**
Don't know if the new logo needs to be red-only shades. If so, I can update.

### CODE REVIEW

**Comment by WesGilster** [comment]
Our last Gradle build went from 2 minutes to 22 minutes! Any idea what happened there?

I like your logo better, but it probably needs to be red... Not sure what you can do about that.

**Comment by WesGilster** [comment]
Well, I ran the build a few times, and I'm guessing Travis is just slow. Hopefully...

**Comment by DanielJoyce** [comment]
Just travis, nothing added except changing the logo.

I can make it red

**Comment by DanielJoyce** [comment]
Set all other color channels to nothing, so that only red channel is used. The parent XCF file is kept the same for now.

**Comment by WesGilster** [comment]
Builds are doing much better today. Under a minute.

**Pull request merged**
