### PR TITLE
I'm trying to make the skins easily costumizable 

### PR DESCRIPTION
**Pull request by kloknibor**
This PR is the start to an easier way of changing skins :)! Which hopefully helps attract people to write skins and keep everything clear.

Done : 
Make GUI folder with all our themes + touchscreen folder
Add API call to find current web GUI theme
Add API call to find current touchscreen GUI theme
Add API call to find available themes web GUI
Add API call to find available touchscreen theme
Add API call to set touchscreen theme
Add API call to change hostGUI variable

To Do : 
Find a way to link /touchscreen to a preset touchscreen theme

Put in order off priority for me :)! The touchscreen stuff looks the hardest so any help is welcome there! The frist 2 I should be able to do myself.

### CODE REVIEW

**Comment by kloknibor** [comment]
@WesGilster I'm having a bit of an hardtime finding out how I got raspberrypi_ip:9091/touchscreen to link to the resources folder chosen in config.properties (touchScreenGUI). Would you mind taking a look into this?

If that's done we can do this PR and I should be fine implementing this in our GUI. Hopefully we can encourage people to make more skins for photonic and make it easy for users to switch between them!

THanks in advance!

**Comment by WesGilster** [comment]
I really like what you did here. This is a pretty cool idea. There are a few things that I think need fixed though, and it will automatically fix your problem in the process. The first thing is that you've put together a directory structure that isn't conducive to reusable front end artifacts and that's going to cause enormous duplication. You've also forced a specific directory structure(albeit a good one) for all GUI designs from this point forward. This means the gui designer has to be intrinsically aware of this structure in order to build their gui. I would rather they "register" specific URLs in the host.properties that correlate to their GUI. This meta information can then be used to change their skin in the gui if they choose. These are simple changes, so I can fix them if you'd like...

**Comment by kloknibor** [comment]
@Wesgilster You have a good point with the duplication issue although the solution is not quite clear to me. But since you seem you do you are more than welcome to implement that! 

Although I think it would be good if the GUI's would life in their own folders instead of randomly in the root. Also it would make detecting off the possible theme's easier, if there is a folder we can detect it. This will make it easier for users without much knowledge to add a costum theme. (Considering that if we get a shitload of themes we might not want to release them all with the stable release/ for manufacturers versions). But also on this point I'm not sure if I understand you properly. If you just mean that we shouldn't return the prefix GUI/webGUI and GUI/touchscreenGUI than I completely agree on that we should strip these :)! If you meant that the resource folders should be able to be anywere and than get linked from the config.properties than I'm not sure if I understand the advantage. But quite possibly you meant neither?

Thanks for taking the time!

**Comment by WesGilster** [comment]
Check out my latest commit. It gives you all of the functionality for skins. I think you'll like it. I also added a method to restart Photonic3D so that all of the changes can take effect. It allows you to have whatever folder structure that the user wants. Whether they want to share folders, or not is dependent on the skin.

**Comment by kloknibor** [comment]
Hmm yours looks fine but seems only for the main skin. It would be quite cool if we can set a seperate homefolder and skin for the touchscreens + I would like the additional API calls I implemented (Which won't work with the new method so we need to reformat that code :))

**Comment by WesGilster** [comment]
Perhaps it's not working(I may have a bug), but what I've designed will support any number of active screens. Linux and Windows have the ability to display on N screens, so if we are going to add functionality to increase past 1, we might as well not limit ourselves to two as you've proposed. For example, you "should" be able to try this:
skins=[{"name":"Main skin", "welcomeFiles":["index.html"], "resourceBase": "resourcesnew", "active": true}, {"name":"Touch Screen Skin", "welcomeFiles":["index.html"], "resourceBase": "/opt/[someOtherRaspberryPiLocation]", "active": true}, {"name":"Green Skin", "welcomeFiles":["index.html"], "resourceBase": "c:\windows\users\someplace", "active": false}]

Your right, I forgot activating and deactivating screens. I've added them in my last commit

**Comment by WesGilster** [comment]
I tested the multiple resource roots. Seems to work ok. Let me know if you have any other issues.

**Comment by WesGilster** [comment]
I haven't tested it, but I'm betting you also get resource sharing between them as well and won't need to duplicate any files.

**Comment by kloknibor** [comment]
I'll give it a shot in the coming days! Sorry for the inactivity but currently moving places ;)!

**Pull request closed without merging**
