### PR TITLE
Update photocentric 10.json

### PR DESCRIPTION
**Pull request by kloknibor**

### CODE REVIEW

**Comment by kloknibor** [comment]
This should fix the problems when running a print on the photocentric printer but my screen broke down so I can't test. I think we might need a delay to fix this 100% but asked in the issues about that already ;)!

**Comment by WesGilster** [comment]
I've pulled your changes, but I'm not sure why or where you would want a delay in your gcode. I would first need to know what event you were waiting to accomplish so that I could wait for that event to happen, and then continue.

**Comment by kloknibor** [comment]
It's so the resin has some settling time and the image won't show untill the motor is back in position.

**Comment by kloknibor** [comment]
So it should be implemented in the Z-lift sequence. james uses G4 S2 command to accomplish this. The firmware of the titan waits till the motor is done moving + 2 seconds than but my firmware doesn't support this so I need some kind of delay I can set to wait for this. It's a bit annoying we can't get information about the firmware being done (I hope you tell me I'm wrong) because we use variable speeds and movement heights...

**Comment by WesGilster** [comment]
It seems that almost every firmware supports the G4. Are you sure that your firmware isn't just measuring in milliseconds instead of seconds? I'd really hate to implement this feature with an external mechanism as it doesn't look pretty.

**Comment by kloknibor** [comment]
Hi Wes I just sended this to your mail with the firmware files too , I´m pretty sure I didn´t miss it but you can take a look yourself.

> A while back I sended you the firmware of the phocontric printer. You mentioned it was a light edited version of GRMBL. I checked the code and I can't seem to find an G4 inside dlp1.c .
> 
> However I can ask if I can just alter the firmware for future printers and send an update to the already printing printers. But well, since the average technical knowledge of the users that isn't gonna be fun! So most likely I will need to help 70% of the costumers through teamviewer if they want to use photonic3d. I currently have also an hardtime with the flashing because it returns me an error that the url is empty while it is programmed in atmel studio and i try to open atmelstudio. Ofcourse I know I need to change the AVRdude links etc but this isn´t the problem. So I´m thinking about using a total new firmware for photocentric printers but well that might make a debugging mess and I haven´t discussed it with photocentric whatsoever.
> 
> Kind regards,
> 
> Robin

**Comment by jmkao** [comment]
You should probably test G4 at the gcode console. According to the GRBL doc, it has been supported since the oldest versions, since it's a basic command. It would be virtually impossible to coordinate motion with other operations without it.

https://github.com/grbl/grbl/wiki

I suggest you try to send the stage up a long distance at a slow rate, like `G1 Z100 F15`.

See if the `OK` comes back right away, or is delayed until after the plate stops moving.

If the `OK` comes back right away, then try `G4 S10` and see if `OK` comes back right away or if it waits until the plate stops moving, or if it waits until 10 seconds after the plate stops moving before displaying `OK`.

**Comment by WesGilster** [comment]
For another project, I bundled avrdude with my distro and then I could program new firmware on the fly. It worked flawlessly. The downside is that I had to compile a million different versions of avrdude for the different OSs and CPU combinations out there. I'm not really sure I want that clutter in this project yet.

It shouldn't, but hopefully their firmware isn't buffering a G4. If so, we have a problem and we are back to the drawing board. Also, I would be nice to know what gcode Photocentric currently uses as this isn't really a unique problem with Photonic3d. It's not as if our software is so fast that this is the first time they have run across this.

**Comment by kloknibor** [comment]
The ok comes back right away... also when sending the G4 command it returns this : 
`error: parse failure: G4 is not supported at line 'G4 S2'` 
And I looked through the complete C file for the firmware and couldn't find the G4 command.... And creation workshop normally has just an delay function, since the speed is static there that isn't a problem, but when we want to go dynamic we have a problem....

**Comment by kloknibor** [comment]
So to make it even worse, there is needed an seperate programmer, it isn't integrated in the board. And the headers need to be soldered on... So all current printerboards will be screwed... Firmware can't be changed easily by us or costumers

**Comment by WesGilster** [comment]
Well, if we need a delay, I can make a delay. I didn't quite get how static vs. dynamic played into the problem.

**Comment by kloknibor** [comment]
The delay in creationworkshop is currently just when the Gcode is send wait x seconds from the firmware. But in creationworkshop photocentric always uses the same lifting speeds and heights and I wanted to use the dynamic lifting heights and speeds. This might be difficult now. 

What we might be able to use is that the firmware for some reason doesn't accept the same gcode directly after each other and just returns an ok without moving. This ok is only returned after the initial movement is finished! This might make it easier to solve does it?

**Comment by WesGilster** [comment]
I'm kindof getting mixed signals from you here. First you are saying we don't have a way to wait in the firmware, but now you say that creationworkshop is waiting x seconds in the firmware. Not quite sure what you mean. Examples would probably be helpful and an explanation for "who"(firmware or firmware driver) is performing the delay. Step one is to get everything working, which it sounds like you have done? Step two is to get the more advanced features working with Photonic3d.

**Comment by kloknibor** [comment]
Sorry, Forgot everything I said and I will try to clarify everything in this single comment, so first the **current firmware facts which might be important here.**
- The firmware doesn't support the G4 command, this is both tested by just sending it and by looking through the firmware
- The firmware is horrible to flash and impossible for normal users of the photocentric printer (requires expensive hardware, taking the printer apart and soldering and more software instructions)
- The firmware doesn't accept a new Gcode command untill the previous command is finished (as seen in the firmware file too)
- The firmware sends an OK straight away when it starts processing the gcode (tested with creation workshop)
- The firmware won't process the gcode if it's exaclty the same as the previous gcode command. So if we would send the Gcode twice we could know when the movement is finished. (tested with creation workshop)

**Facts about the current setup with creation workshop :** 

The Gcode bit for the lift sequence is as following : 

```
;********** Lift Sequence ********
G1{$SlideTiltVal != 0? X$SlideTiltVal:} Z($ZLiftDist * $ZDir) F{$CURSLICE < $NumFirstLayers?$ZBottomLiftRate:$ZLiftRate}
G1{$SlideTiltVal != 0? X($SlideTiltVal * -1):} Z(($LayerThickness-$ZLiftDist) * $ZDir) F$ZRetractRate
;<Delay> %d($ZLiftDist*60000/$ZRetractRate+200)
;********** Lift Sequence **********

```

Because the lift height and speed is the same for every layer the creationworkshop function `<delay>` can be used because this delay will always be the same.

**What I want for photonic3D :** 

Currently it doesn't work at all like I would like too. The display shows the slice as soon as the motor starts moving. I might be able to fix this by sending the gcode twice but than I still can't add an delay so the resin can settle like what is possible with the G4 command.

ultimately I want to use the lift height calculator and lift speed calculator. But I think if we fix the above thing this will be possible without a problem.

**My proposal :** 

Add an delay function to creation workshop. So if we use <delay> S2 it would wait like 2 Seconds (or maybe even better make milliseconds of this). I will properly test my solution to find out if the movement is done with photonic3d. If this works than indeed only the <delay> function is needed.

Hope this makes it easier to understand instead of making it harder! Thanks! And feel free to think with!

**Comment by WesGilster** [comment]
It sounds like their commands are being buffered which means an M400 should wait until the buffer is clear. If they aren't buffering, then their firmware is broken and they probably need to know about something like that. Either way, I can still create the delay method, but essentially this is an awful hack around for bad firmware...

**Comment by kloknibor** [comment]
I just checked and no M400 code is present... And well it's rubbish to the max... If you could make the delay function that would be great ;)! Thanks!

**Comment by kloknibor** [comment]
Hmmm I was testing with photonic3d now and I seem to have new errors, will report on them tonight

**Comment by kloknibor** [comment]
If you can make the delay code work for me than I can atleast make the static profile available for now and will try to get the dynamic ones available with some tricks ;)! So if you can do that for me you will make me and 2 beta testers quite happy :)

**Comment by WesGilster** [comment]
It sounds like there isn't much choice here. I'll put together a delay after work.

**Comment by kloknibor** [comment]
Thank you very much Wes! Your awesome :D!

**Comment by WesGilster** [comment]
This was already implemented for creation workshop scene files. I've now opened it up for all printable file types. The syntax is identical to creation workshop:

`; <delay> FreeMarkerTemplate`

A side effect of this change is that all gcode going through cws files will now allow be FreeMarkerTemplate driven as well. This means that you should also test with .cws files to ensure their gcode works as well.

**Comment by kloknibor** [comment]
Thanks, that is exactly what I needed :)! I will make a new pull request later this week or maybe tonight!

**Comment by kloknibor** [comment]
Hmm So I just tried it but it failed with an error sating : Status: Failed No match found

I don't see anything in the logfile... Did I do something wrong?

THis is the template for the movement now (I use the M18 to wait till the movement is done :)) 

G1 Z${ZLiftDist} F${ZLiftRate};
G1 Z-${(ZLiftDist - LayerThickness)} F180;
M18;
; <delay> 10000;

here is the log file : 

[LogBundle (5).zip.pdf](https://github.com/WesGilster/Creation-Workshop-Host/files/364793/LogBundle.5.zip.pdf)

**Comment by WesGilster** [comment]
I had a bug in my code, but what you have above would not work in Creation Workshop or Photonic3d. I wrote a test for something like this:

```
G1 Z${ZLiftDist} F${ZLiftRate}
G1 Z-${(ZLiftDist - LayerThickness)} F180;
M18
; <    dElAy >   ${ZLiftDist * ZLiftRate};
;
```

but in Creation Workshop you've probably used something like this:

`; <Delay>   ${ZLiftDist * ZLiftRate}`

dist \* rate should precisely be what you are looking for a dynamic time frame.

**Comment by WesGilster** [comment]
Actually I'm guessing ZLiftRate is measured in MM per second so you might have to take the result times 1000.

**Comment by kloknibor** [comment]
Thanks for your input!

I tested tonight without the delay code. It moved like it was supposed too. It went up slow, came down quick and because of the M18 code it waited to show the next slice untill the motors were done moving. 

But the resin needs some time to settle so it isn't moving anymore when we start curing the new layer. So I only use the delay time to wait en period of time to let the resin settle which is a static number. Than this should do what I want right? I just want the delay function to wait every slice like 1,5 second

**Comment by kloknibor** [comment]
I tested this and it worked like a charm! I will do a new PR

**Comment by WesGilster** [comment]
Nice to hear. I'm glad it's working for you.

**Comment by WesGilster** [comment]
I'll be putting together a new build for production soon as I've fixed a bunch of customer bugs and they have just been sitting around in our dev branch. I'd like those to go out. I noticed you haven't created a PR for this change yet. In order to get your printer operational, this might be a good time.

**Comment by kloknibor** [comment]
sorry Didn't read this untill now I'll do it straight away

**Pull request merged**
