### PR TITLE
add update on start functionality for windows and Wanhao D7 compatibility 

### PR DESCRIPTION
**Pull request by kloknibor**
we might want to discuss splitting windows and linux archives to save some download time :) This would add 2-3MB just to allow windows to update when starting... Also it can be more advanced but for now it does the job for me ;)!

### CODE REVIEW

**Comment by kloknibor** [comment]
also we might want to clean out the CURL directory but didn't got time yet to check what we need to leave there and what not (because off al the licenses and such)

**Comment by kloknibor** [comment]
I also added the Wanhao D7 profile to this :)!

**Comment by WesGilster** [comment]
I just tried to test this and I get this:
Microsoft Windows [Version 10.0.10586]
(c) 2015 Microsoft Corporation. All rights reserved.

C:\Users\wgilster>start.bat
The system cannot find the path specified.
FINDSTR: Cannot open build.number
C:\Users\wgilster\start.bat(44, 5) Microsoft JScript runtime error: File not found

Network TAG:
Local TAG : ~13
Download URL =
The system cannot find the path specified.
'unzip' is not recognized as an internal or external command,
operable program or batch file.

**Comment by draakie2017** [comment]
Whoops that is really weird... I'll take a look at it tonight, for me it ran smooth :/ you did leave the start.bat in the root of your extracted zip file right?

**Comment by draakie2017** [comment]
(Oh by the way Robin here as well ;p didn't realise I was logged on on this account :)

**Comment by kloknibor** [comment]
can you please try the start.bat from this release on your PC? : https://github.com/draakie2017/Photonic3D-Dev/releases/download/Currax3D-0.49/C.Users.Robin.Documents.GitHub.Photonic3D-Dev.host.photonic-Currax3D-0.49.zip

it works fine for me... If you are trying to say the script can be improved than yes I agree! (by checking dependencies and more error handling)

**Comment by WesGilster** [comment]
I see, so what you are saying is that you still first need to download, unzip and execute the batch script the first time. Wasn't sure how the script works.

**Comment by draakie2017** [comment]
Hi Wes,

Yes that's correct, I'll bring it at the level of start.sh sometime though ;)! So than you'll only need start.bat, but currently it will update the existing folder.

I did this since I rely on the unzip and curl dependencies. But I can merge them in an exe file if desired :)

**Pull request merged**
