### PR TITLE
Update photocentric 10.json

### PR DESCRIPTION
**Pull request by kloknibor**

### CODE REVIEW

**Comment by kloknibor** [comment]
Only thing I still miss is the  
`<PauseOnPrinterResponseRegEx>.*door.*open.*</PauseOnPrinterResponseRegEx>` I've had this added to the profile before I thought but I can't seem to find it... Can you give me an hint? And I'll add it

**Comment by WesGilster** [comment]
I'll just put it in for you, but you are going to want to test this. I think you might find that it's easier to use your existing printer configuration to be sure you aren't missing anything(It should be quite a bit easier than doing a diff yourself).  Plus, you don't have to worry about manually encoding chars which may break json marshalling.

You can get a list of all your printer configs with this:
`http://[raspberryPiIP]:9091/services/printers/list`

If you've forgotten all of the restful APIs, the developer documentation is bundled directly with the application and each method is documented here:
`http://[raspberryPiIP]:9091/apidoc`

**Comment by kloknibor** [comment]
I won't be home much soon, but I'll try asap, will be a few days but thanks for adding!

**Comment by kloknibor** [comment]
This returns an error when trying to process the .json I'll look into it tomorrow

**Pull request merged**
